#!/usr/bin/env ruby

# txt = ["#hashcatch no 1 album is Thriller",
#        "my #3 CD is the Bible #hc"]
# txt.map { |s| handle_status(s) }


TweetStream.configure do |config|
  config.consumer_key       = 'X5sbEkdNPXBbd2c8hqog'
  config.consumer_secret    = 'bPeAmHaUdH4J5mY8n9NpGvcvtlCxIuUrcXSvJjkc'
  config.oauth_token        = '460113372-uNucdi2XaWwmVeAxyTNSEb0z0qXRFOfaylg7ECLj'
  config.oauth_token_secret = 'xFrY9FSPca0cCFjAxKDk3mGGHyJI94MXac0a1y5pBI'
  config.auth_method        = :oauth
end



# This will pull a sample of all tweets based on
# your Twitter account's Streaming API role.
TweetStream::Client.new.track(TOP3_HASHTAG) do |status|
  puts "RECV"
  handle_status(status)
end
